server {
    listen 80;
    listen [::]:80;
    server_name wedding24.uz www.wedding24.uz;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://wedding24.uz$request_uri;
    }
}
