"use client"

import { useTranslation } from "react-i18next"

const storefrontKeys = [
  "catalogEyebrow",
  "catalogTitle",
  "catalogDescription",
  "productsEyebrow",
  "productsTitle",
  "productsFound",
  "productsFoundFor",
  "mobileFilters",
  "previousPage",
  "nextPage",
  "paginationPage",
  "allCategories",
  "categories",
  "searchCategories",
  "applyFilters",
  "newest",
  "priceLow",
  "priceHigh",
  "filters",
  "clearFilters",
  "priceRange",
  "priceFrom",
  "priceTo",
  "subcategories",
  "colors",
  "sizes",
  "showMore",
  "showLess",
  "unnamedColor",
  "loadingOptions",
  "noOptions",
  "colorRed",
  "colorGreen",
  "colorBlue",
  "colorBlack",
  "colorWhite",
  "colorYellow",
  "colorBrown",
  "colorGray",
  "colorPink",
  "colorPurple",
  "colorKhaki",
  "addToCart",
  "adding",
  "favorite",
  "unfavorite",
  "noProducts",
  "productsError",
  "retry",
  "signInRequired",
  "signIn",
  "addedToCart",
  "addedToFavorites",
  "removedFromFavorites",
  "outOfStock",
  "actionError",
  "favoritesTitle",
  "favoritesDescription",
  "favoritesEmptyTitle",
  "favoritesEmptyDescription",
  "cartTitle",
  "cartDescription",
  "cartEmptyTitle",
  "cartEmptyDescription",
  "popularProducts",
  "clearCart",
  "remove",
  "itemTotal",
  "total",
  "checkout",
  "checkoutDescription",
  "checkoutContactStep",
  "checkoutDeliveryStep",
  "checkoutReviewStep",
  "checkoutContactTitle",
  "checkoutContactDescription",
  "checkoutDeliveryTitle",
  "checkoutDeliveryDescription",
  "checkoutReviewTitle",
  "checkoutReviewDescription",
  "recipientName",
  "recipientFirstName",
  "recipientLastName",
  "recipientPhone",
  "deliveryAddress",
  "deliveryCity",
  "deliveryDistrict",
  "street",
  "houseNumber",
  "apartmentNumber",
  "entrance",
  "floor",
  "addressComment",
  "deliveryLocation",
  "deliveryLocationDescription",
  "optional",
  "requiredField",
  "invalidPhoneNumber",
  "previousStep",
  "nextStep",
  "note",
  "placeOrder",
  "placingOrder",
  "checkoutError",
  "orderSuccess",
  "orderSuccessDescription",
  "orderNumber",
  "myOrders",
  "ordersDescription",
  "ordersEmptyTitle",
  "ordersEmptyDescription",
  "order",
  "orderedAt",
  "cancelOrder",
  "orderCancelled",
  "pieces",
  "searchPlaceholder",
  "searchResults",
  "searchHint",
  "searchEmpty",
  "searchError",
  "searchClose",
  "withoutCategory",
  "favoritesNav",
  "cartNav",
  "cartDelivery",
  "orderSummary",
  "subtotal",
  "shippingCost",
  "freeShipping",
  "productDiscount",
  "promoCodes",
  "promoCodePlaceholder",
  "promoCodesUnavailable",
  "proceedToCheckout",
  "recommendations",
  "signInCheckout",
  "backToCart",
  "statusNew",
  "statusConfirmed",
  "statusShipped",
  "statusDelivered",
  "statusCancelled",
  "moreOrderItems",
] as const

type StorefrontKey = (typeof storefrontKeys)[number]
type StorefrontCopy = Record<StorefrontKey, string>

export function useStorefrontCopy() {
  const { t } = useTranslation()

  return Object.fromEntries(
    storefrontKeys.map((key) => [key, t(`storefront.${key}`)])
  ) as StorefrontCopy
}
