/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export interface AddressCreateDTO {
  label?: string;
  /** @minLength 1 */
  recipientName: string;
  /**
     * @minLength 1
     * @pattern ^\+998\d{9}$
     */
  phone: string;
  /** @minLength 1 */
  addressLine: string;
  isDefault?: boolean;
}
