/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export interface AddressDTO {
  id?: number;
  label?: string;
  recipientName?: string;
  phone?: string;
  addressLine?: string;
  default?: boolean;
}
