/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export interface AttachmentDTO {
  id?: number;
  fileName?: string;
  fileType?: string;
  fileSize?: number;
  s3Url?: string;
  s3Key?: string;
  organizationId?: number;
}
