/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export type BackupAuditUpsertDTOStatus = typeof BackupAuditUpsertDTOStatus[keyof typeof BackupAuditUpsertDTOStatus];


export const BackupAuditUpsertDTOStatus = {
  STARTED: 'STARTED',
  SKIPPED: 'SKIPPED',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
} as const;
