/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { BackupAuditDTOStatus } from './backupAuditDTOStatus';
import type { BackupAuditDTOType } from './backupAuditDTOType';

export interface BackupAuditDTO {
  id?: number;
  runId?: string;
  type?: BackupAuditDTOType;
  status?: BackupAuditDTOStatus;
  serverName?: string;
  fileName?: string;
  localPath?: string;
  logFileName?: string;
  logLocalPath?: string;
  s3Bucket?: string;
  s3Key?: string;
  s3LogKey?: string;
  fileSizeBytes?: number;
  startedAt?: string;
  finishedAt?: string;
  durationMs?: number;
  errorMessage?: string;
  createdAt?: string;
  updatedAt?: string;
}
