/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export interface BackupPolicyUpdateDTO {
  dailyEnabled: boolean;
  weeklyEnabled: boolean;
  monthlyEnabled: boolean;
  /** @minimum 1 */
  dailyRetentionDays: number;
  /** @minimum 1 */
  weeklyRetentionWeeks: number;
  /** @minimum 1 */
  monthlyRetentionMonths: number;
  s3Bucket?: string;
  s3Prefix?: string;
  active: boolean;
}
