/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { BackupAuditUpsertDTOStatus } from './backupAuditUpsertDTOStatus';
import type { BackupAuditUpsertDTOType } from './backupAuditUpsertDTOType';

export interface BackupAuditUpsertDTO {
  /** @minLength 1 */
  runId: string;
  type: BackupAuditUpsertDTOType;
  status: BackupAuditUpsertDTOStatus;
  startedAt: string;
  finishedAt?: string;
  serverName?: string;
  fileName?: string;
  localPath?: string;
  logFileName?: string;
  logLocalPath?: string;
  s3Bucket?: string;
  s3Key?: string;
  s3LogKey?: string;
  fileSizeBytes?: number;
  durationMs?: number;
  errorMessage?: string;
}
