/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export interface BackupPolicyDTO {
  id?: number;
  dailyEnabled?: boolean;
  weeklyEnabled?: boolean;
  monthlyEnabled?: boolean;
  dailyRetentionDays?: number;
  weeklyRetentionWeeks?: number;
  monthlyRetentionMonths?: number;
  s3Bucket?: string;
  s3Prefix?: string;
  active?: boolean;
}
