/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export type BackupAuditUpsertDTOType = typeof BackupAuditUpsertDTOType[keyof typeof BackupAuditUpsertDTOType];


export const BackupAuditUpsertDTOType = {
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY',
  MONTHLY: 'MONTHLY',
} as const;
