/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export interface BranchDTO {
  id?: number;
  name?: string;
  phone?: string;
  address?: string;
  latitude?: number;
  longitude?: number;
  organizationId?: number;
  organizationName?: string;
  active?: boolean;
}
