/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { Branch } from './branch';

export interface BranchAnalyticsDTO {
  from?: string;
  to?: string;
  branches?: Branch[];
}
