/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export interface BranchCreateDTO {
  /** @minLength 1 */
  name: string;
  phone?: string;
  address?: string;
  latitude?: number;
  longitude?: number;
  organizationId?: number;
}
