/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export interface BrowserHandoffExchangeRequest {
  /**
     * @minLength 1
     * @pattern [A-Za-z0-9_-]{43}
     */
  code: string;
}
