/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { MaybeInaccessibleMessage } from './maybeInaccessibleMessage';
import type { User } from './user';

export interface CallbackQuery {
  id?: string;
  from?: User;
  message?: MaybeInaccessibleMessage;
  inline_message_id?: string;
  data?: string;
  game_short_name?: string;
  chat_instance?: string;
}
