/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { CategoryUpdateDTOSizeType } from './categoryUpdateDTOSizeType';

export interface CategoryUpdateDTO {
  /** @minLength 1 */
  name: string;
  nameRu?: string;
  nameEng?: string;
  descriptionUz?: string;
  descriptionRu?: string;
  descriptionEng?: string;
  sizeType: CategoryUpdateDTOSizeType;
  organizationId?: number;
  parentId?: number;
  imageId?: number;
  active?: boolean;
}
