/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export type CategoryDTOSizeType = typeof CategoryDTOSizeType[keyof typeof CategoryDTOSizeType];


export const CategoryDTOSizeType = {
  LETTER: 'LETTER',
  NUMBER: 'NUMBER',
} as const;
