/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { CategoryDTOSizeType } from './categoryDTOSizeType';

export interface CategoryDTO {
  id?: number;
  name?: string;
  description?: string;
  sizeType?: CategoryDTOSizeType;
  imageUrl?: string;
  active?: boolean;
  productCount?: number;
}
