/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export type CategoryCreateDTOSizeType = typeof CategoryCreateDTOSizeType[keyof typeof CategoryCreateDTOSizeType];


export const CategoryCreateDTOSizeType = {
  LETTER: 'LETTER',
  NUMBER: 'NUMBER',
} as const;
