/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export interface ChatPhoto {
  small_file_id?: string;
  small_file_unique_id?: string;
  big_file_id?: string;
  big_file_unique_id?: string;
}
