/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { ChatBoostSource } from './chatBoostSource';

export interface ChatBoost {
  boost_id?: string;
  add_date?: number;
  expiration_date?: number;
  source?: ChatBoostSource;
}
