/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { ChatMessageCreateDTOType } from './chatMessageCreateDTOType';

export interface ChatMessageCreateDTO {
  type?: ChatMessageCreateDTOType;
  /**
     * @minLength 0
     * @maxLength 5000
     */
  text?: string;
  attachmentId?: number;
  replyToMessageId?: number;
}
