/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export type ChatRoomDTOStatus = typeof ChatRoomDTOStatus[keyof typeof ChatRoomDTOStatus];


export const ChatRoomDTOStatus = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
} as const;
