/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { ChatRoomDTOStatus } from './chatRoomDTOStatus';

export interface ChatRoomDTO {
  id?: number;
  customerId?: number;
  customerName?: string;
  organizationId?: number;
  organizationName?: string;
  branchId?: number;
  branchName?: string;
  status?: ChatRoomDTOStatus;
  createdAt?: string;
  updatedAt?: string;
}
