/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { Chat } from './chat';
import type { ChatInviteLink } from './chatInviteLink';
import type { ChatMember } from './chatMember';
import type { User } from './user';

export interface ChatMemberUpdated {
  chat?: Chat;
  from?: User;
  date?: number;
  old_chat_member?: ChatMember;
  new_chat_member?: ChatMember;
  invite_link?: ChatInviteLink;
  via_chat_folder_invite_link?: boolean;
}
