/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { Chat } from './chat';
import type { ChatBoostSource } from './chatBoostSource';

export interface ChatBoostRemoved {
  chat?: Chat;
  boost_id?: string;
  remove_date?: number;
  source?: ChatBoostSource;
}
