/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';

export interface ChatInviteLink {
  invite_link?: string;
  creator?: User;
  is_primary?: boolean;
  is_revoked?: boolean;
  expire_date?: number;
  member_limit?: number;
  name?: string;
  pending_join_request_count?: number;
  creates_join_request?: boolean;
}
