/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { ChatLocation } from './chatLocation';
import type { ChatPermissions } from './chatPermissions';
import type { ChatPhoto } from './chatPhoto';
import type { Message } from './message';
import type { ReactionType } from './reactionType';

export interface Chat {
  id?: number;
  type?: string;
  title?: string;
  first_name?: string;
  last_name?: string;
  username?: string;
  photo?: ChatPhoto;
  description?: string;
  invite_link?: string;
  pinned_message?: Message;
  sticker_set_name?: string;
  can_set_sticker_set?: boolean;
  permissions?: ChatPermissions;
  slow_mode_delay?: number;
  bio?: string;
  linked_chat_id?: number;
  location?: ChatLocation;
  message_auto_delete_time?: number;
  has_private_forwards?: boolean;
  has_protected_content?: boolean;
  join_to_send_messages?: boolean;
  join_by_request?: boolean;
  has_restricted_voice_and_video_messages?: boolean;
  is_forum?: boolean;
  active_usernames?: string[];
  emoji_status_custom_emoji_id?: string;
  has_aggressive_anti_spam_enabled?: boolean;
  has_hidden_members?: boolean;
  emoji_status_expiration_date?: boolean;
  available_reactions?: ReactionType[];
  accent_color_id?: number;
  background_custom_emoji_id?: string;
  profile_accent_color_id?: boolean;
  profile_background_custom_emoji_id?: string;
  has_visible_history?: boolean;
  unrestrict_boost_count?: number;
  custom_emoji_sticker_set_name?: boolean;
}
