/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { Chat } from './chat';
import type { ChatInviteLink } from './chatInviteLink';
import type { User } from './user';

export interface ChatJoinRequest {
  chat?: Chat;
  from?: User;
  date?: number;
  bio?: string;
  invite_link?: ChatInviteLink;
  user_chat_id?: number;
}
