/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { AttachmentDTO } from './attachmentDTO';
import type { ChatMessageDTOType } from './chatMessageDTOType';

export interface ChatMessageDTO {
  id?: number;
  roomId?: number;
  senderId?: number;
  senderName?: string;
  type?: ChatMessageDTOType;
  text?: string;
  attachment?: AttachmentDTO;
  replyToMessageId?: number;
  replyToText?: string;
  replyToSenderId?: number;
  replyToSenderName?: string;
  createdAt?: string;
}
