/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export type ChatMessageCreateDTOType = typeof ChatMessageCreateDTOType[keyof typeof ChatMessageCreateDTOType];


export const ChatMessageCreateDTOType = {
  TEXT: 'TEXT',
  IMAGE: 'IMAGE',
  FILE: 'FILE',
} as const;
