/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export interface CheckoutDTO {
  recipientName?: string;
  recipientFirstName?: string;
  recipientLastName?: string;
  /**
     * @minLength 1
     * @pattern ^\+998\d{9}$
     */
  recipientPhone: string;
  deliveryAddress?: string;
  deliveryCity?: string;
  deliveryDistrict?: string;
  street?: string;
  houseNumber?: string;
  apartmentNumber?: string;
  entrance?: string;
  floor?: string;
  /**
     * @minimum -90
     * @maximum 90
     */
  latitude?: number;
  /**
     * @minimum -180
     * @maximum 180
     */
  longitude?: number;
  addressComment?: string;
  note?: string;
}
