/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export interface CheckoutDTO {
  /** @minLength 1 */
  recipientName: string;
  /**
     * @minLength 1
     * @pattern ^\+998\d{9}$
     */
  recipientPhone: string;
  /** @minLength 1 */
  deliveryAddress: string;
  note?: string;
}
