/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { Location } from './location';
import type { User } from './user';

export interface ChosenInlineQuery {
  result_id?: string;
  from?: User;
  location?: Location;
  inline_message_id?: string;
  query?: string;
}
