/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export interface ClickConnectionTestRequest {
  /**
     * @minLength 1
     * @pattern CLICK
     */
  provider: string;
  enabled: boolean;
  /**
     * @minLength 0
     * @maxLength 100
     */
  merchantId: string;
  /**
     * @minLength 0
     * @maxLength 100
     */
  serviceId: string;
  /**
     * @minLength 0
     * @maxLength 100
     */
  merchantUserId?: string;
  /**
     * @minLength 0
     * @maxLength 500
     */
  secretKey: string;
  /**
     * @minLength 0
     * @maxLength 500
     */
  checkoutUrl: string;
}
