/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export interface ClickPaymentSettingsResponse {
  organizationId?: number;
  clickEnabled?: boolean;
  clickRealMode?: boolean;
  clickMerchantId?: string;
  clickServiceId?: string;
  clickMerchantUserId?: string;
  clickSecretConfigured?: boolean;
}
