/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export interface ClickCallbackResponse {
  error?: number;
  click_trans_id?: number;
  merchant_trans_id?: string;
  merchant_prepare_id?: number;
  error_note?: string;
}
