/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export interface ClickPaymentSettingsRequest {
  clickEnabled?: boolean;
  clickRealMode?: boolean;
  /**
     * @minLength 0
     * @maxLength 100
     */
  clickMerchantId?: string;
  /**
     * @minLength 0
     * @maxLength 100
     */
  clickServiceId?: string;
  /**
     * @minLength 0
     * @maxLength 100
     */
  clickMerchantUserId?: string;
  /**
     * @minLength 0
     * @maxLength 500
     */
  clickSecretKey?: string;
}
