/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export interface ColorDTO {
  id?: number;
  name?: string;
  nameUz?: string;
  nameRu?: string;
  nameEng?: string;
  hexCode?: string;
  organizationId?: number;
  organizationName?: string;
}
