/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export interface ColorCreateDTO {
  /** @minLength 1 */
  name: string;
  /**
     * @minLength 1
     * @pattern ^#([A-Fa-f0-9]{6})$
     */
  hexCode: string;
}
