/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export interface Contact {
  phone_number?: string;
  first_name?: string;
  last_name?: string;
  user_id?: number;
  vcard?: string;
}
