/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { Animation } from './animation';
import type { Audio } from './audio';
import type { Contact } from './contact';
import type { Dice } from './dice';
import type { Document } from './document';
import type { Game } from './game';
import type { Giveaway } from './giveaway';
import type { GiveawayWinners } from './giveawayWinners';
import type { Invoice } from './invoice';
import type { LinkPreviewOptions } from './linkPreviewOptions';
import type { Location } from './location';
import type { MessageOrigin } from './messageOrigin';
import type { PhotoSize } from './photoSize';
import type { Poll } from './poll';
import type { Sticker } from './sticker';
import type { Story } from './story';
import type { Venue } from './venue';
import type { Video } from './video';
import type { VideoNote } from './videoNote';
import type { Voice } from './voice';

export interface ExternalReplyInfo {
  origin?: MessageOrigin;
  chat?: unknown;
  message_id?: number;
  link_preview_options?: LinkPreviewOptions;
  animation?: Animation;
  audio?: Audio;
  document?: Document;
  photo?: PhotoSize[];
  sticker?: Sticker;
  story?: Story;
  video?: Video;
  video_note?: VideoNote;
  voice?: Voice;
  has_media_spoiler?: boolean;
  contact?: Contact;
  dice?: Dice;
  game?: Game;
  giveaway?: Giveaway;
  giveaway_winners?: GiveawayWinners;
  invoice?: Invoice;
  location?: Location;
  poll?: Poll;
  venue?: Venue;
}
