/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { ProductListDTO } from './productListDTO';

export interface FlashSaleDTO {
  active?: boolean;
  endsAt?: string;
  products?: ProductListDTO[];
}
