/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export interface ForgotPasswordResponseDTO {
  otpSent?: boolean;
  telegramLinked?: boolean;
  message?: string;
  botUsername?: string;
  botLink?: string;
  telegramUsername?: string;
}
