/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { Animation } from './animation';
import type { MessageEntity } from './messageEntity';
import type { PhotoSize } from './photoSize';

export interface Game {
  title?: string;
  description?: string;
  photo?: PhotoSize[];
  text?: string;
  text_entities?: MessageEntity[];
  animation?: Animation;
}
