/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export type GetAll1Type = typeof GetAll1Type[keyof typeof GetAll1Type];


export const GetAll1Type = {
  LETTER: 'LETTER',
  NUMBER: 'NUMBER',
} as const;
