/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export type GetAll13Status = typeof GetAll13Status[keyof typeof GetAll13Status];


export const GetAll13Status = {
  STARTED: 'STARTED',
  SKIPPED: 'SKIPPED',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
} as const;
