/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export type GetAll6Params = {
active?: boolean;
organizationId?: number;
search?: string;
page?: number;
size?: number;
};
