/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export type GetAll12Status = typeof GetAll12Status[keyof typeof GetAll12Status];


export const GetAll12Status = {
  STARTED: 'STARTED',
  SKIPPED: 'SKIPPED',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
} as const;
