/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { GetAll3Status } from './getAll3Status';

export type GetAll3Params = {
organizationId?: number;
productId?: number;
status?: GetAll3Status;
/**
 * @minimum 0
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
size?: number;
};
