/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export type GetAll9Status = typeof GetAll9Status[keyof typeof GetAll9Status];


export const GetAll9Status = {
  STARTED: 'STARTED',
  SKIPPED: 'SKIPPED',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
} as const;
