/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export type GetAll3Status = typeof GetAll3Status[keyof typeof GetAll3Status];


export const GetAll3Status = {
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;
