/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { GetAll8Status } from './getAll8Status';

export type GetAll8Params = {
status?: GetAll8Status;
page?: number;
size?: number;
};
