/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { GetAll12Status } from './getAll12Status';

export type GetAll12Params = {
status?: GetAll12Status;
productId?: number;
categoryId?: number;
regionId?: number;
districtId?: number;
/**
 * @minimum 0
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
size?: number;
};
