/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { GetAll11Status } from './getAll11Status';

export type GetAll11Params = {
status?: GetAll11Status;
page?: number;
size?: number;
};
