/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export type GetAll2Params = {
active?: boolean;
organizationId?: number;
branchId?: number;
categoryId?: number;
search?: string;
minPrice?: number;
maxPrice?: number;
colorId?: number;
sizeId?: number;
sort?: string;
page?: number;
size?: number;
};
