/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { GetAll1Type } from './getAll1Type';

export type GetAll1Params = {
type?: GetAll1Type;
};
