/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { GetAll13Status } from './getAll13Status';
import type { GetAll13Type } from './getAll13Type';

export type GetAll13Params = {
type?: GetAll13Type;
status?: GetAll13Status;
page?: number;
size?: number;
};
