/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { GetAll12Status } from './getAll12Status';
import type { GetAll12Type } from './getAll12Type';

export type GetAll12Params = {
type?: GetAll12Type;
status?: GetAll12Status;
page?: number;
size?: number;
};
