/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { GetAll7Status } from './getAll7Status';

export type GetAll7Params = {
status?: GetAll7Status;
page?: number;
size?: number;
};
