/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { Message } from './message';

export interface GiveawayCompleted {
  winner_count?: number;
  unclaimed_prize_count?: number;
  giveaway_message?: Message;
}
