/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';

export interface GiveawayWinners {
  chat?: unknown;
  giveaway_message_id?: number;
  winners_selection_date?: number;
  winner_count?: number;
  winners?: User[];
  additional_chat_count?: number;
  premium_subscription_month_count?: number;
  unclaimed_prize_count?: number;
  only_new_members?: boolean;
  was_refunded?: boolean;
  prize_description?: string;
}
