/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { Chat } from './chat';

export interface Giveaway {
  chats?: Chat[];
  winners_selection_date?: number;
  winner_count?: number;
  only_new_members?: boolean;
  has_public_winners?: boolean;
  prize_description?: string;
  country_codes?: string[];
  premium_subscription_month_count?: number;
}
