/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { CallbackGame } from './callbackGame';
import type { LoginUrl } from './loginUrl';
import type { WebAppInfo } from './webAppInfo';

export interface InlineKeyboardButton {
  text?: string;
  url?: string;
  callback_data?: string;
  callback_game?: CallbackGame;
  switch_inline_query?: string;
  switch_inline_query_current_chat?: string;
  pay?: boolean;
  login_url?: LoginUrl;
  web_app?: WebAppInfo;
}
