/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { InlineKeyboardButton } from './inlineKeyboardButton';

export interface InlineKeyboardMarkup {
  inline_keyboard?: InlineKeyboardButton[][];
}
