/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { PhotoSize } from './photoSize';

export interface Invoice {
  title?: string;
  description?: string;
  start_parameter?: string;
  currency?: string;
  total_amount?: number;
  photo?: PhotoSize;
}
