/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { UserDTO } from './userDTO';

export interface JwtDTO {
  accessToken?: string;
  tokenType?: string;
  user?: UserDTO;
}
