/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export interface LoginUrl {
  url?: string;
  forward_text?: string;
  bot_username?: string;
  request_write_access?: boolean;
}
