/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export interface LoginDTO {
  /** @minLength 1 */
  emailOrPhone: string;
  /** @minLength 1 */
  password: string;
}
