/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export interface MaybeInaccessibleMessage {
  chatId?: number;
  messageId?: number;
  superGroupMessage?: boolean;
  groupMessage?: boolean;
  userMessage?: boolean;
  date?: number;
}
