/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { Chat } from './chat';
import type { ReactionType } from './reactionType';
import type { User } from './user';

export interface MessageReactionUpdated {
  chat?: Chat;
  message_id?: number;
  user?: User;
  actor_chat?: Chat;
  date?: number;
  old_reaction?: ReactionType[];
  new_reaction?: ReactionType[];
}
