/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';

export interface MessageEntity {
  type?: string;
  offset?: number;
  length?: number;
  url?: string;
  user?: User;
  language?: string;
  custom_emoji_id?: string;
}
