/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { Chat } from './chat';
import type { ReactionCount } from './reactionCount';

export interface MessageReactionCountUpdated {
  chat?: Chat;
  message_id?: number;
  date?: number;
  reactions?: ReactionCount[];
}
