/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export type MyOrdersParams = {
productId?: number;
categoryId?: number;
regionId?: number;
districtId?: number;
/**
 * @minimum 0
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
size?: number;
};
