/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export type NotificationDTOType = typeof NotificationDTOType[keyof typeof NotificationDTOType];


export const NotificationDTOType = {
  CHAT_MESSAGE: 'CHAT_MESSAGE',
  ORDER_STATUS: 'ORDER_STATUS',
  SYSTEM: 'SYSTEM',
} as const;
