/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { OrderDTOStatus } from './orderDTOStatus';
import type { OrderItemDTO } from './orderItemDTO';

export interface OrderDTO {
  id?: number;
  orderNumber?: string;
  status?: OrderDTOStatus;
  statusLabel?: string;
  totalAmount?: number;
  recipientName?: string;
  recipientPhone?: string;
  deliveryAddress?: string;
  note?: string;
  createdAt?: string;
  items?: OrderItemDTO[];
}
