/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export type OrderDTOPaymentMethod = typeof OrderDTOPaymentMethod[keyof typeof OrderDTOPaymentMethod];


export const OrderDTOPaymentMethod = {
  CASH: 'CASH',
  CLICK: 'CLICK',
} as const;
