/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export interface OrderItemDTO {
  id?: number;
  variantId?: number;
  productName?: string;
  colorName?: string;
  sizeValue?: string;
  unitPrice?: number;
  quantity?: number;
  subtotal?: number;
}
