/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { AttachmentDTO } from './attachmentDTO';

export interface OrganizationDTO {
  id?: number;
  name?: string;
  description?: string;
  contactPerson?: string;
  contactEmail?: string;
  contactPhone?: string;
  inn?: string;
  address?: string;
  logo?: AttachmentDTO;
  active?: boolean;
}
