/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export interface OrganizationCreateDTO {
  /** @minLength 1 */
  name: string;
  description?: string;
  contactPerson?: string;
  contactEmail?: string;
  contactPhone?: string;
  /** @pattern ^[0-9]{9,14}$ */
  inn?: string;
  address?: string;
  logoId?: number;
}
