/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { OrganizationAdvertisementResponse } from './organizationAdvertisementResponse';

export interface PageResponseOrganizationAdvertisementResponse {
  content?: OrganizationAdvertisementResponse[];
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
  last?: boolean;
}
