/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { EncryptedCredentials } from './encryptedCredentials';
import type { EncryptedPassportElement } from './encryptedPassportElement';

export interface PassportData {
  data?: EncryptedPassportElement[];
  credentials?: EncryptedCredentials;
}
