/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { MessageEntity } from './messageEntity';
import type { PollOption } from './pollOption';

export interface Poll {
  id?: string;
  question?: string;
  options?: PollOption[];
  total_voter_count?: number;
  is_closed?: boolean;
  is_anonymous?: boolean;
  type?: string;
  allows_multiple_answers?: boolean;
  correct_option_id?: number;
  open_period?: number;
  close_date?: number;
  explanation?: string;
  explanation_entities?: MessageEntity[];
}
