/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { Chat } from './chat';
import type { User } from './user';

export interface PollAnswer {
  poll_id?: string;
  user?: User;
  option_ids?: number[];
  voter_chat?: Chat;
}
