/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { OrderInfo } from './orderInfo';
import type { User } from './user';

export interface PreCheckoutQuery {
  id?: string;
  from?: User;
  currency?: string;
  total_amount?: number;
  invoice_payload?: string;
  shipping_option_id?: string;
  order_info?: OrderInfo;
}
