/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { ProductImageDTO } from './productImageDTO';
import type { ProductVariantDTO } from './productVariantDTO';

export interface ProductDTO {
  id?: number;
  name?: string;
  description?: string;
  categoryId?: number;
  categoryName?: string;
  organizationId?: number;
  organizationName?: string;
  basePrice?: number;
  discountPercent?: number;
  discountedPrice?: number;
  active?: boolean;
  ratingAvg?: number;
  ratingCount?: number;
  images?: ProductImageDTO[];
  variants?: ProductVariantDTO[];
}
