/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export interface ProductVariantDTO {
  id?: number;
  colorId?: number;
  colorName?: string;
  colorHex?: string;
  sizeId?: number;
  sizeValue?: string;
  stock?: number;
  price?: number;
  effectivePrice?: number;
  active?: boolean;
}
