/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { ProductImageDTO } from './productImageDTO';
import type { ProductVariantDTO } from './productVariantDTO';

export interface ProductDTO {
  id?: number;
  name?: string;
  nameRu?: string;
  nameEng?: string;
  descriptionUz?: string;
  descriptionRu?: string;
  descriptionEng?: string;
  categoryId?: number;
  categoryName?: string;
  organizationId?: number;
  organizationName?: string;
  organizationAddress?: string;
  organizationLatitude?: number;
  organizationLongitude?: number;
  branchId?: number;
  branchName?: string;
  branchAddress?: string;
  branchLatitude?: number;
  branchLongitude?: number;
  basePrice?: number;
  amount?: number;
  discountPercent?: number;
  discountedPrice?: number;
  active?: boolean;
  ratingAvg?: number;
  ratingCount?: number;
  videoAttachmentId?: number;
  videoUrl?: string;
  images?: ProductImageDTO[];
  variants?: ProductVariantDTO[];
}
