/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export interface ProductTransferItemResponse {
  id?: number;
  sourceVariantId?: number;
  targetVariantId?: number;
  colorName?: string;
  colorHex?: string;
  sizeValue?: string;
  quantity?: number;
  sourceStockBefore?: number;
  sourceStockAfter?: number;
  targetStockBefore?: number;
  targetStockAfter?: number;
}
