/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export type ProductTransferResponseStatus = typeof ProductTransferResponseStatus[keyof typeof ProductTransferResponseStatus];


export const ProductTransferResponseStatus = {
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;
