/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export interface ProductListDTO {
  id?: number;
  name?: string;
  categoryId?: number;
  categoryName?: string;
  basePrice?: number;
  discountPercent?: number;
  discountedPrice?: number;
  mainImageUrl?: string;
  totalStock?: number;
  active?: boolean;
  ratingAvg?: number;
  ratingCount?: number;
}
