/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export interface ProductImageDTO {
  id?: number;
  attachmentId?: number;
  url?: string;
  main?: boolean;
  sortOrder?: number;
}
