/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export interface ProductListDTO {
  id?: number;
  name?: string;
  nameRu?: string;
  nameEng?: string;
  categoryId?: number;
  categoryName?: string;
  organizationId?: number;
  organizationName?: string;
  organizationAddress?: string;
  organizationLatitude?: number;
  organizationLongitude?: number;
  branchId?: number;
  branchName?: string;
  branchAddress?: string;
  branchLatitude?: number;
  branchLongitude?: number;
  basePrice?: number;
  amount?: number;
  discountPercent?: number;
  discountedPrice?: number;
  mainImageUrl?: string;
  videoUrl?: string;
  totalStock?: number;
  active?: boolean;
  ratingAvg?: number;
  ratingCount?: number;
}
