/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { ProductTransferItemResponse } from './productTransferItemResponse';
import type { ProductTransferResponseStatus } from './productTransferResponseStatus';

export interface ProductTransferResponse {
  id?: number;
  sourceOrganizationId?: number;
  sourceOrganizationName?: string;
  targetOrganizationId?: number;
  targetOrganizationName?: string;
  sourceProductId?: number;
  sourceProductName?: string;
  targetProductId?: number;
  targetProductName?: string;
  status?: ProductTransferResponseStatus;
  note?: string;
  createdById?: number;
  createdAt?: string;
  cancelledAt?: string;
  items?: ProductTransferItemResponse[];
}
