/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export interface ProductTransferItemRequest {
  sourceVariantId: number;
  targetVariantId: number;
  /** @minimum 1 */
  quantity: number;
}
