/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { ProductImageCreateDTO } from './productImageCreateDTO';
import type { ProductVariantCreateDTO } from './productVariantCreateDTO';

export interface ProductUpdateDTO {
  /** @minLength 1 */
  name: string;
  description?: string;
  categoryId: number;
  organizationId?: number;
  basePrice: number;
  /**
     * @minimum 0
     * @maximum 100
     */
  discountPercent?: number;
  active?: boolean;
  images?: ProductImageCreateDTO[];
  variants?: ProductVariantCreateDTO[];
}
