/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { ProductTransferItemRequest } from './productTransferItemRequest';

export interface ProductTransferCreateRequest {
  sourceProductId: number;
  targetProductId: number;
  note?: string;
  /** @minItems 1 */
  items: ProductTransferItemRequest[];
}
