/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export interface PublicStatsResponse {
  activeClients?: number;
  monthlyRevenue?: number;
  branches?: number;
  organizations?: number;
  regions?: number;
  monthStart?: string;
}
