/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { DailySales } from './dailySales';
import type { Metric } from './metric';

export interface SalesAnalyticsDTO {
  from?: string;
  to?: string;
  revenue?: Metric;
  orders?: Metric;
  averageCheck?: Metric;
  dailySales?: DailySales[];
}
