/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { ShippingAddress } from './shippingAddress';
import type { User } from './user';

export interface ShippingQuery {
  id?: string;
  from?: User;
  invoice_payload?: string;
  shipping_address?: ShippingAddress;
}
