/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export interface ShippingAddress {
  country_code?: string;
  state?: string;
  city?: string;
  street_line1?: string;
  street_line2?: string;
  post_code?: string;
}
