/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { SizeCreateDTOType } from './sizeCreateDTOType';

export interface SizeCreateDTO {
  /** @minLength 1 */
  value: string;
  type: SizeCreateDTOType;
  sortOrder?: number;
  organizationId?: number;
}
