/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { SizeDTOType } from './sizeDTOType';

export interface SizeDTO {
  id?: number;
  value?: string;
  type?: SizeDTOType;
  sortOrder?: number;
}
