/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export type SizeCreateDTOType = typeof SizeCreateDTOType[keyof typeof SizeCreateDTOType];


export const SizeCreateDTOType = {
  LETTER: 'LETTER',
  NUMBER: 'NUMBER',
} as const;
