/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export type SizeDTOType = typeof SizeDTOType[keyof typeof SizeDTOType];


export const SizeDTOType = {
  LETTER: 'LETTER',
  NUMBER: 'NUMBER',
} as const;
