/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { File } from './file';
import type { MaskPosition } from './maskPosition';
import type { PhotoSize } from './photoSize';

export interface Sticker {
  file_id?: string;
  file_unique_id?: string;
  type?: string;
  width?: number;
  height?: number;
  thumbnail?: PhotoSize;
  file_size?: number;
  emoji?: string;
  set_name?: string;
  mask_position?: MaskPosition;
  is_animated?: boolean;
  is_video?: boolean;
  premium_animation?: File;
  custom_emoji_id?: string;
  needs_repainting?: boolean;
}
