/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { MessageEntity } from './messageEntity';

export interface TextQuote {
  text?: string;
  entities?: MessageEntity[];
  position?: number;
  is_manual?: boolean;
}
