/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export type UpdateOrderStatusDTOStatus = typeof UpdateOrderStatusDTOStatus[keyof typeof UpdateOrderStatusDTOStatus];


export const UpdateOrderStatusDTOStatus = {
  NEW: 'NEW',
  CONFIRMED: 'CONFIRMED',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
} as const;
