/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { CallbackQuery } from './callbackQuery';
import type { ChatBoostRemoved } from './chatBoostRemoved';
import type { ChatBoostUpdated } from './chatBoostUpdated';
import type { ChatJoinRequest } from './chatJoinRequest';
import type { ChatMemberUpdated } from './chatMemberUpdated';
import type { ChosenInlineQuery } from './chosenInlineQuery';
import type { InlineQuery } from './inlineQuery';
import type { Message } from './message';
import type { MessageReactionCountUpdated } from './messageReactionCountUpdated';
import type { MessageReactionUpdated } from './messageReactionUpdated';
import type { Poll } from './poll';
import type { PollAnswer } from './pollAnswer';
import type { PreCheckoutQuery } from './preCheckoutQuery';
import type { ShippingQuery } from './shippingQuery';

export interface Update {
  update_id?: number;
  message?: Message;
  inline_query?: InlineQuery;
  chosen_inline_result?: ChosenInlineQuery;
  callback_query?: CallbackQuery;
  edited_message?: Message;
  channel_post?: Message;
  edited_channel_post?: Message;
  shipping_query?: ShippingQuery;
  pre_checkout_query?: PreCheckoutQuery;
  poll?: Poll;
  poll_answer?: PollAnswer;
  my_chat_member?: ChatMemberUpdated;
  chat_member?: ChatMemberUpdated;
  chat_join_request?: ChatJoinRequest;
  message_reaction?: MessageReactionUpdated;
  message_reaction_count?: MessageReactionCountUpdated;
  chat_boost?: ChatBoostUpdated;
  removed_chat_boost?: ChatBoostRemoved;
}
