/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { UserCreateDTOGender } from './userCreateDTOGender';

export interface UserCreateDTO {
  /** @minLength 1 */
  firstname: string;
  /** @minLength 1 */
  lastname: string;
  /** @minLength 1 */
  email: string;
  /**
     * @minLength 6
     * @maxLength 2147483647
     */
  password: string;
  /**
     * @minLength 1
     * @pattern ^\+998\d{9}$
     */
  phone: string;
  age?: number;
  gender?: UserCreateDTOGender;
}
