/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { UserUpdateDTOGender } from './userUpdateDTOGender';

export interface UserUpdateDTO {
  firstname?: string;
  lastname?: string;
  phone?: string;
  age?: number;
  gender?: UserUpdateDTOGender;
  organizationId?: number;
}
