/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { AttachmentDTO } from './attachmentDTO';
import type { UserDTOGender } from './userDTOGender';

export interface UserDTO {
  id?: number;
  firstname?: string;
  lastname?: string;
  email?: string;
  phone?: string;
  age?: number;
  gender?: UserDTOGender;
  photo?: AttachmentDTO;
  organizationId?: number;
  organizationName?: string;
  branchId?: number;
  branchName?: string;
  roles?: string[];
}
