/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export type UserUpdateDTOGender = typeof UserUpdateDTOGender[keyof typeof UserUpdateDTOGender];


export const UserUpdateDTOGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
} as const;
