/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export type UserUpdateDTORolesItem = typeof UserUpdateDTORolesItem[keyof typeof UserUpdateDTORolesItem];


export const UserUpdateDTORolesItem = {
  ROLE_ADMIN: 'ROLE_ADMIN',
  ROLE_USER: 'ROLE_USER',
  ROLE_EMPLOYER: 'ROLE_EMPLOYER',
  ROLE_SUPER_ADMIN: 'ROLE_SUPER_ADMIN',
} as const;
