/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { PhotoSize } from './photoSize';

export interface Video {
  file_id?: string;
  file_unique_id?: string;
  width?: number;
  height?: number;
  duration?: number;
  thumbnail?: PhotoSize;
  mime_type?: string;
  file_size?: number;
  file_name?: string;
}
