/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */
import type { PhotoSize } from './photoSize';

export interface VideoNote {
  file_id?: string;
  file_unique_id?: string;
  length?: number;
  duration?: number;
  thumbnail?: PhotoSize;
  file_size?: number;
}
