/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Humayro API
 * Humayro e-commerce API
 * OpenAPI spec version: 1.0
 */

export interface Voice {
  file_id?: string;
  file_unique_id?: string;
  duration?: number;
  mime_type?: string;
  file_size?: number;
}
